### ISSUE TITLE
[Observer] Use ControllerRevision owner OwnerReferences to match to Daemonset

### ISSUE THREAD

**Issue by Jacobious52** [atlassian-labs/cyclops#26]
Currently ControllerRevision is matched to Daemonset with Label Selector. ControllerRevision now has OwnerReferences like Pods. 

```yaml
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: ds-name
    uid: 9eb7d74c-efc7-44aa-83c9-b61ec7626471
```

This should simply the ControllerRevision to Daemonset mapping and remove the potential of error using labels.

We currently do this for Pods so we can easily migrate the existing functionality to ControllerRevision as well.
